### ISSUE TITLE
TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by matheusml** [leandrowd/react-responsive-carousel#120]
Hi,

after I added this lib in my project, which is working great btw, I'm having this weird error when I try to test the application (with Jest):

```
TypeError: Cannot read property 'addEventListener' of null
      
      at Carousel.setupAutoPlay (node_modules/react-responsive-carousel/lib/components/Carousel.js:363:32)
      at Carousel.setupCarousel (node_modules/react-responsive-carousel/lib/components/Carousel.js:333:22)
      at Carousel.componentDidMount (node_modules/react-responsive-carousel/lib/components/Carousel.js:295:18)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:206:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:153:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.render (node_modules/react-test-renderer/lib/ReactTestMount.js:125:18)
      at Object.<anonymous> (src/components/home/intro/Intro.spec.js:7:47)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)

```

This is the simple test, that's breaking:

```js
import React from 'react';
import renderer from 'react-test-renderer';

import Intro from './Intro';

test('Snapshot', () => {
  const component = renderer.create(<Intro />);
  let tree = component.toJSON();
  expect(tree).toMatchSnapshot();
});
```

**Comment by leandrowd** [comment]
Hey @matheusml, I think I found (and fixed) the issue. Please update to the latest version and let me know how it goes.

**Comment by leandrowd** [comment]
Hi @matheusml, I'm closing this issue due to inactivity. Feel free to reopen if you need.
