### ISSUE TITLE
Thumbs in React Server Rendering

### ISSUE THREAD

**Issue by dcatanzaro** [leandrowd/react-responsive-carousel#162]
Hi.

I used this component in my project with Server Rendering, when showThumbs this errors appears:

`app.js:12 Cannot read property 'clientWidth' of undefined
TypeError: Cannot read property 'clientWidth' of undefined
    at t.n.updateSizes (http://localhost:4000/_next/7d948023-c6b9-441a-b25d-c8bae4843fd4/page/property:3:2591)
    at t.value (http://localhost:4000/_next/7d948023-c6b9-441a-b25d-c8bae4843fd4/page/property:3:4510)
    at t.value (http://localhost:4000/_next/7d948023-c6b9-441a-b25d-c8bae4843fd4/page/property:3:3896)
    at S (http://localhost:4000/_next/93837ce9c4103961f59ff26c8571f67e/app.js:11:18031)
    at v (http://localhost:4000/_next/93837ce9c4103961f59ff26c8571f67e/app.js:11:18232)
    at Object.O (http://localhost:4000/_next/93837ce9c4103961f59ff26c8571f67e/app.js:11:23193)
    at Object.a [as render] (http://localhost:4000/_next/93837ce9c4103961f59ff26c8571f67e/app.js:2:685)
    at http://localhost:4000/_next/93837ce9c4103961f59ff26c8571f67e/app.js:12:2221
    at r (http://localhost:4000/_next/93837ce9c4103961f59ff26c8571f67e/app.js:11:1835)
    at Generator._invoke (http://localhost:4000/_next/93837ce9c4103961f59ff26c8571f67e/app.js:11:2955)`

Same to #29 but with thumbs.

Thanks!

**Comment by hashrocketeer** [comment]
I am getting the same error with `showThumbs={false}` and normal client side rendering

This happens on load without the user taking any action.

![image](https://user-images.githubusercontent.com/317960/30886271-14b8bb96-a2dc-11e7-8300-ef239fef62dd.png)
