### ISSUE TITLE
React Server Rendering..?

### ISSUE THREAD

**Issue by stephen-last** [leandrowd/react-responsive-carousel#85]
I'm guessing this component isn't compatible with React server rendering..?

```
ReferenceError: window is not defined
    at null.componentWillMount (C:\node\crusader-uk\node_modules\react-responsive-carousel\lib\components\Thumbs.js:47:9)
    at C:\node\crusader-uk\node_modules\react-dom\lib\ReactCompositeComponent.js:348:23
    at measureLifeCyclePerf (C:\node\crusader-uk\node_modules\react-dom\lib\ReactCompositeComponent.js:75:12)
    at null.ReactCompositeComponent.performInitialMount (C:\node\crusader-uk\node_modules\react-dom\lib\ReactCompositeComponent.js:347:9)
    at null.ReactCompositeComponent.mountComponent (C:\node\crusader-uk\node_modules\react-dom\lib\ReactCompositeComponent.js:258:21)
    at Object.ReactReconciler.mountComponent (C:\node\crusader-uk\node_modules\react-dom\lib\ReactReconciler.js:46:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (C:\node\crusader-uk\node_modules\react-dom\lib\ReactMultiChild.js:238:44)
    at ReactDOMComponent.Mixin._createContentMarkup (C:\node\crusader-uk\node_modules\react-dom\lib\ReactDOMComponent.js:653:32)
    at ReactDOMComponent.Mixin.mountComponent (C:\node\crusader-uk\node_modules\react-dom\lib\ReactDOMComponent.js:520:29)
    at Object.ReactReconciler.mountComponent (C:\node\crusader-uk\node_modules\react-dom\lib\ReactReconciler.js:46:35)
```

Any plans to support server rendering..?

**Comment by leandrowd** [comment]
Hi @stephen-last, I haven't implemented yet because I never needed. Making it SSR compatible shouldn't be a big deal. Probably just moving what is on `componentWillMount` to `componentDidMount` should be enough. 

Unfortunately, I don't have any available time to do the changes but, if you keen on fixing it, I would happily approve a Pull Request.

**Comment by stephen-last** [comment]
@leandrowd Thanks for the fast reply... Unfortunately I don't have the time either, I'm on the look out for a carousel that works for me right now. I'll keep this repo in mind though and may come back later when I do have time.

Thanks again!

**Comment by leandrowd** [comment]
Hi @stephen-last, I've moved the event bindings to componentDidMount and I believe it will be enough to fix your problem. Try the latest version and let me know if you still have issues ;)

Cheers

**Comment by leandrowd** [comment]
I'm closing this issue as per the comment above. Feel free to reopen if you have issues.

**Comment by stephen-last** [comment]
@leandrowd Morning! Really sorry for the late response. I've just tried this and it works now, server rendering nicely, so you can add that to your list of features. Many thanks for your time on this! :-)
